language: python
dist: xenial
sudo: true

python:
  - 3.9

services:
  - postgresql
addons:
  postgresql: '13.3'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env_sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres"

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
